services:
  mysql:
    image: mysql:8.0
    restart: always

    network_mode: host

    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d

    command: --log-bin-trust-function-creators=1